### PR TITLE
Migrate Wc vendors to dokan

### LINKED ISSUE #17: Hpos support Wc-vendor

### PR DESCRIPTION
**Pull request by Aunshon**
Updated code and folder structure

* Closes: #17

When test:

- Make sure vendor settings page has no error like map box or google map.

### CODE REVIEW

**Comment by shashwatahalder01** [comment]
Scenario:
Migration Notice shouldn't be visible on the migration dashboard.

Screenshot at Sep 15 14-40-31

**Comment by shashwatahalder01** [comment]
scenario:
- [x] Not all orders are migrating 
- [ ] No retry option for failed migration
- [x] Showing congratulations message even though not all data are migrated

Screenshot:
Screenshot at Sep 15 17-05-20

**Comment by shashwatahalder01** [comment]
@Aunshon 
Scenario: 

WC vendors withdraw rule:  Commission is received by the `vendor` and triggered when the order status is `processing` or `completed`.  There are two statuses `Due`, and `Paid`  to indicate whether the commission is received by the vendor or not.

In PR, commissions from orders with `processing/completed` + `paid` status are converted to withdrawal amount/ vendor balance, which isn't right cause those commissions are already received by the vendor and no longer need withdrawal.

Only orders with `processing/completed` + `Due` status should be converted to withdrawal amount/vendor balance


Steps to reproduce:
1. place order on wc vendors
2. mark order as paid in WC vendors > commission menu
3. migrate to dokan 
4. go to vendor withdraw menu 

Screenshot:
Screenshot at Nov 30 17-08-08
Screenshot at Nov 30 17-08-34
Screenshot at Nov 30 17-08-45

**Comment by shashwatahalder01** [comment]
@Aunshon 
Scenario:
toggle suborder or show suborder doesn't work after migration. suborders display by default. doesn't  hide if clicked toggle suborder


Steps to reproduce: 
1. place multivendor order on wc vendor
2. migrate to dokan
3. go to woocommerce orders

Screenshot:
Screenshot at Nov 30 16-33-14

**Comment by Aunshon** [comment]
> @Aunshon Scenario: toggle suborder or show suborder doesn't work after migration. suborders display by default. doesn't hide if clicked toggle suborder
> 
> Steps to reproduce:
> 
> 1. place multivendor order on wc vendor
> 2. migrate to dokan
> 3. go to woocommerce orders
> 
> Screenshot: Screenshot at Nov 30 16-33-14

This is a dokan lite issue.

**Pull request merged**
